name: Give Strava Kudos

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

env:
  STRAVA_EMAIL: ${{ secrets.STRAVA_EMAIL }}
  STRAVA_PASSWORD: ${{ secrets.STRAVA_PASSWORD }}
jobs:
  run-kudos-cron:
    runs-on:  ubuntu-20.04 #ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4 #actions/checkout@v3 
      - uses: actions/setup-node@v4 #actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: playwright install
      - run: python give_kudos.py
